CREATE TABLE IF NOT EXISTS PUBLIC.GENRE (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50),
    CONSTRAINT CONSTRAINT_40 PRIMARY KEY (ID)
    );

-- PUBLIC.RATING определение

-- Drop table

-- DROP TABLE PUBLIC.RATING;

CREATE TABLE IF NOT EXISTS PUBLIC.RATING (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME CHARACTER VARYING(100),
    CONSTRAINT CONSTRAINT_8 PRIMARY KEY (ID)
    );

-- PUBLIC.USERS определение

-- Drop table

-- DROP TABLE PUBLIC.USERS;

CREATE TABLE IF NOT EXISTS PUBLIC.USERS (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    EMAIL CHARACTER VARYING(100) NOT NULL,
    LOGIN CHARACTER VARYING(100) NOT NULL,
    NAME CHARACTER VARYING(100),
    BIRTHDAY DATE,
    CONSTRAINT CONSTRAINT_4 PRIMARY KEY (ID)
    );

    CREATE UNIQUE INDEX IF NOT EXISTS USER_EMAIL_UINDEX
    ON PUBLIC.USERS (EMAIL);

    -- Создание уникального индекса для столбца LOGIN
    CREATE UNIQUE INDEX IF NOT EXISTS USER_LOGIN_UINDEX
    ON PUBLIC.USERS (LOGIN);

-- PUBLIC.FILMS определение

-- Drop table

-- DROP TABLE PUBLIC.FILMS;

CREATE TABLE IF NOT EXISTS PUBLIC.FILMS (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME CHARACTER VARYING(100) NOT NULL,
    DESCRIPTION CHARACTER VARYING(200) NOT NULL,
    RELEASE_DATE DATE NOT NULL,
    DURATION INTEGER NOT NULL,
    RATING CHARACTER VARYING(15),
    CONSTRAINT CONSTRAINT_3 PRIMARY KEY (ID),
    CONSTRAINT CONSTRAINT_3F FOREIGN KEY (RATING) REFERENCES PUBLIC.RATING(ID) ON DELETE CASCADE ON UPDATE RESTRICT
    );

-- PUBLIC.FRIENDS определение

-- Drop table

-- DROP TABLE PUBLIC.FRIENDS;

CREATE TABLE IF NOT EXISTS PUBLIC.FRIENDS (
    USER_ID BIGINT,
    FRIEND_ID BIGINT,
    CONSTRAINT CONSTRAINT_7 FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS(ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT CONSTRAINT_70 FOREIGN KEY (FRIEND_ID) REFERENCES PUBLIC.USERS(ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
    PRIMARY KEY (USER_ID, FRIEND_ID)
    );

-- PUBLIC.FILM_GENRE определение

-- Drop table

-- DROP TABLE PUBLIC.FILM_GENRE;

CREATE TABLE IF NOT EXISTS PUBLIC.FILM_GENRE (
    FILM_ID BIGINT,
    GENRE_ID BIGINT,
    CONSTRAINT CONSTRAINT_79 FOREIGN KEY (FILM_ID) REFERENCES PUBLIC.FILMS(ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT CONSTRAINT_79D FOREIGN KEY (GENRE_ID) REFERENCES PUBLIC.GENRE(ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
    PRIMARY KEY (FILM_ID, GENRE_ID)
    );

-- PUBLIC.FILM_LIKES определение

-- Drop table

-- DROP TABLE PUBLIC.FILM_LIKES;

CREATE TABLE IF NOT EXISTS PUBLIC.FILM_LIKES (
    FILM_ID BIGINT,
    USER_ID BIGINT,
    CONSTRAINT CONSTRAINT_7A FOREIGN KEY (FILM_ID) REFERENCES PUBLIC.FILMS(ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT CONSTRAINT_7A1 FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS(ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
    PRIMARY KEY (FILM_ID,USER_ID)
    );