create TABLE IF NOT EXISTS PUBLIC.GENRE (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50),
    CONSTRAINT CONSTRAINT_40 PRIMARY KEY (ID)
    );

-- PUBLIC.RATING определение

-- Drop table

-- DROP TABLE PUBLIC.RATING;

create TABLE IF NOT EXISTS PUBLIC.RATING (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME CHARACTER VARYING(100),
    CONSTRAINT CONSTRAINT_8 PRIMARY KEY (ID)
    );

-- PUBLIC.USERS определение

-- Drop table

-- DROP TABLE PUBLIC.USERS;

create TABLE IF NOT EXISTS PUBLIC.USERS (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    EMAIL CHARACTER VARYING(100) NOT NULL,
    LOGIN CHARACTER VARYING(100) NOT NULL,
    NAME CHARACTER VARYING(100),
    BIRTHDAY DATE,
    CONSTRAINT CONSTRAINT_4 PRIMARY KEY (ID)
    );

    create unique index IF NOT EXISTS USER_EMAIL_UINDEX
    ON PUBLIC.USERS (EMAIL);

    -- Создание уникального индекса для столбца LOGIN
    create unique index IF NOT EXISTS USER_LOGIN_UINDEX
    ON PUBLIC.USERS (LOGIN);

-- PUBLIC.FILMS определение

-- Drop table

-- DROP TABLE PUBLIC.FILMS;

create TABLE IF NOT EXISTS PUBLIC.FILMS (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME CHARACTER VARYING(100) NOT NULL,
    DESCRIPTION CHARACTER VARYING(200) NOT NULL,
    RELEASE_DATE DATE NOT NULL,
    DURATION INTEGER NOT NULL,
    RATING CHARACTER VARYING(15),
    CONSTRAINT CONSTRAINT_3 PRIMARY KEY (ID),
    CONSTRAINT CONSTRAINT_3F FOREIGN KEY (RATING) REFERENCES PUBLIC.RATING(ID) ON  DELETE CASCADE ON UPDATE RESTRICT
    );

-- PUBLIC.FRIENDS определение

-- Drop table

-- DROP TABLE PUBLIC.FRIENDS;

create TABLE IF NOT EXISTS PUBLIC.FRIENDS (
    USER_ID BIGINT,
    FRIEND_ID BIGINT,
    CONSTRAINT CONSTRAINT_7 FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS(ID) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT CONSTRAINT_70 FOREIGN KEY (FRIEND_ID) REFERENCES PUBLIC.USERS(ID) ON DELETE CASCADE ON UPDATE RESTRICT,
    PRIMARY KEY (USER_ID, FRIEND_ID)
    );

-- PUBLIC.FILM_GENRE определение

-- Drop table

-- DROP TABLE PUBLIC.FILM_GENRE;

create TABLE IF NOT EXISTS PUBLIC.FILM_GENRE (
    FILM_ID BIGINT,
    GENRE_ID BIGINT,
    CONSTRAINT CONSTRAINT_79 FOREIGN KEY (FILM_ID) REFERENCES PUBLIC.FILMS(ID) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT CONSTRAINT_79D FOREIGN KEY (GENRE_ID) REFERENCES PUBLIC.GENRE(ID) ON DELETE CASCADE ON UPDATE RESTRICT,
    PRIMARY KEY (FILM_ID, GENRE_ID)
    );

-- PUBLIC.FILM_LIKES определение

-- Drop table

-- DROP TABLE PUBLIC.FILM_LIKES;

create TABLE IF NOT EXISTS PUBLIC.FILM_LIKES (
    FILM_ID BIGINT,
    USER_ID BIGINT,
    CONSTRAINT CONSTRAINT_7A FOREIGN KEY (FILM_ID) REFERENCES PUBLIC.FILMS(ID) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT CONSTRAINT_7A1 FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS(ID) ON DELETE CASCADE ON UPDATE RESTRICT,
    PRIMARY KEY (FILM_ID,USER_ID)
    );

-- PUBLIC.EVENTS_FEED определение

CREATE TABLE IF NOT EXISTS PUBLIC.EVENTS_FEED (
    event_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id BIGINT REFERENCES USERS ON DELETE CASCADE,
    event_type CHARACTER VARYING(100) NOT NULL,
    operation CHARACTER VARYING(100) NOT NULL,
    entity_id BIGINT
);

CREATE TABLE IF NOT EXISTS PUBLIC.REVIEWS (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    CONTENT VARCHAR(5000) NOT NULL,
    IS_POSITIVE BOOLEAN NOT NULL,
    USER_ID BIGINT NOT NULL,
    FILM_ID BIGINT NOT NULL,
    USEFUL INT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS(ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
    FOREIGN KEY (FILM_ID) REFERENCES PUBLIC.FILMS(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS PUBLIC.REVIEWS_LIKES (
    USER_ID BIGINT NOT NULL,
    REVIEW_ID BIGINT NOT NULL,
    IS_LIKE BOOLEAN NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (REVIEW_ID) REFERENCES PUBLIC.REVIEWS(ID) ON DELETE CASCADE,
    PRIMARY KEY (USER_ID, REVIEW_ID)
    );
-- PUBLIC.DIRECTORS определение

-- Drop table

-- DROP TABLE PUBLIC.DIRECTORS;

create TABLE IF NOT EXISTS PUBLIC.DIRECTORS (
	ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME CHARACTER VARYING(255) NOT NULL,
    CONSTRAINT CONSTRAINT_D PRIMARY KEY (ID)
);

-- PUBLIC.DIRECTOR_FILM определение

-- Drop table

-- DROP TABLE PUBLIC.DIRECTOR_FILM;

create TABLE IF NOT EXISTS PUBLIC.FILM_DIRECTOR (
	FILM_ID 		BIGINT,
	DIRECTOR_ID 	BIGINT,
	CONSTRAINT CONSTRAINT_D1 FOREIGN KEY (FILM_ID) REFERENCES PUBLIC.FILMS(ID) ON delete RESTRICT ON update RESTRICT,
    CONSTRAINT CONSTRAINT_D2 FOREIGN KEY (DIRECTOR_ID) REFERENCES PUBLIC.DIRECTORS(ID) ON delete RESTRICT ON update RESTRICT,
	PRIMARY KEY (FILM_ID, DIRECTOR_ID)
);